language: php
sudo: false

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false

env:
  matrix:
    - DEPENDENCIES="highest"
    - DEPENDENCIES="lowest"
install:
  - composer global require hirak/prestissimo:^0.3.7
  - if [[ "$DEPENDENCIES" = 'highest' ]]; then travis_retry composer update --no-suggest; fi
  - if [[ "$DEPENDENCIES" = 'lowest' ]]; then travis_retry composer update --no-suggest --prefer-lowest; fi

script:
  - composer check-style
  - composer test
  - if [[ $(phpenv version-name) == "7.1" ]] && [[ "$DEPENDENCIES" = 'highest' ]]; then composer metrics; fi

after_success:
  - if [[ $(phpenv version-name) == "7.1" ]] && [[ "$DEPENDENCIES" = 'highest' ]]; then bash <(curl -s https://codecov.io/bash) -f ./clover.xml; fi
