language: php
sudo: false

php:
  - 7.1
  - 7.2
  - nightly

env:
  matrix:
    - DEPENDENCIES="highest"
    - DEPENDENCIES="lowest"
install:
  - composer global require hirak/prestissimo:^0.3.7
  - if [[ "$DEPENDENCIES" = 'highest' ]]; then travis_retry composer update --no-suggest; fi
  - if [[ "$DEPENDENCIES" = 'lowest' ]]; then travis_retry composer update --no-suggest --prefer-lowest; fi

script:
  - composer test

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache