language: php
sudo: false

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

notifications:
  email: false

env:
  global:
    - COMPOSER_OPTIONS="--no-suggest --no-interaction"
  matrix:
    - DEPENDENCIES="--prefer-lowest"
    - DEPENDENCIES=""
install:
  - composer global require hirak/prestissimo:^0.3.7
  - travis_retry composer update $COMPOSER_OPTIONS $DEPENDENCIES
  - composer show

script:
  - composer check-style
  - composer analyze
  - composer test
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then composer metrics; fi

after_success:
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then bash <(curl -s https://codecov.io/bash) -f ./clover.xml; fi
